### ISSUE TITLE
Requesting ability to turn off file output 

### ISSUE THREAD

**Issue by sandimas** [huangli712/ACFlow#1]
First off, ACFlow is looking great so far. Great work!

I am looking to incorporate ACFlow into an in-house Julia DQMC project which is in development. Because everything will be in Julia we have no need for the default ACFlow file output. Could you add a variable to disable file output? I think adding it in the [BASE] section of the toml (or in our case B dictionary) would probably be the easiest way to handle it without making the code any more complicated for the non-Julia users.

Thanks,
James Neuhaus
Steve Johnston Group

**Comment by huangli712** [comment]
Thank you for your suggestion. This feature is already implemented. Please set [BASE] -> fwrite to false.  See https://huangli712.github.io/projects/acflow/man/param.html#fwrite
for more details.

Li
