### ISSUE TITLE
A question about the input standard deviation

### ISSUE THREAD

**Issue by wangfh5** [huangli712/ACFlow#2]
Thank you for providing the excellent package and documents for analytical continuation. I am new to DQMC and analytical continuation, and I have noticed that there is a mix-up in the terminology used in the codes regarding ”standard deviation“ and ”error“. This has caused confusion for me, particularly when it comes to the input "standard deviation" for ACFlow. I would like to clarify whether it should be the actual standard deviation $\sigma=\sqrt{\frac{\sum_{i=1}^n \left(x_i-\bar{x}\right)^2}{n}}$, or the standard error $\sigma_n=\frac{\sigma}{\sqrt{n}}$ (where $n$ represents the number of samples). For my data, the standard deviations maybe large while standard errors are smaller. And I am afraid that standard deviations are too noisy.

**Comment by huangli712** [comment]
Thank you for your question. When I use the terminology `standard deviation` or `error bar` in the codes or documentations, actually what I mean is $\sigma = \sqrt{   \frac{ (x - \bar{x})^2  }  { n (n-1) } }$.

Li

**Comment by wangfh5** [comment]
Thanks for your reply.That would be clear.
